title: "AI-SOC Automation Blog"
description: "Insights, updates, and research from the AI-SOC Automation project."
baseurl: ""
url: "https://ai-soc-automation.github.io/blog-source"

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true